### ISSUE TITLE
Some questions about the command 'run evaluate.py'

### ISSUE THREAD

**Issue by MelonLee-go** [Tsinghua-MARS-Lab/HDMapNet#16]
Hi, thank you for your complete and great code.
When i tried to use the command 'python evaluate.py' as readme.md said, I got some error message:
`AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`
I have trained the model, but i can't solve the problem above.
Besides, there is another question: i could't find a argument named 'result_path' as your readme.md said. Should i add the argument by myself or the version of code has some different?
Thank you for your time.

**Comment by MelonLee-go** [comment]
![Uploading error_message.png…]()

**Comment by MelonLee-go** [comment]
![error_message](https://user-images.githubusercontent.com/58371402/165206260-62f30107-665e-41ac-9735-bcb3abc521b0.png)

**Comment by Vishal1711** [comment]
Did you solve this error? I am facing the same issue.

**Comment by Vishal1711** [comment]
#20 @MelonLee-go This may help.

**Comment by MelonLee-go** [comment]
Hello~Thank you for your time! I have sovled this problem!

**Comment by VenkateshCBR** [comment]
Did you successfully visualize the prediction? or were you able to run `vis_pred.py` ?
If yes, can you share the command you run or changes you did in `vis_pred.py`?

**Comment by VenkateshCBR** [comment]
@MelonLee-go 
Did you successfully visualize the prediction? or were you able to run `vis_pred.py` ?
If yes, can you share the command you run or changes you did in `vis_pred.py`?
