### ISSUE TITLE
question about GT generation

### ISSUE THREAD

**Issue by LegendBC** [Tsinghua-MARS-Lab/HDMapNet#17]
Thanks for the great work! I run the vis_labe.py following the readme. And I found that the gt lines projected on surrounding views had some misalignment with the real line elements. The results may be attributed to supposing the Z=0 for all map elements in https://github.com/Tsinghua-MARS-Lab/HDMapNet/blob/main/vis_label.py#L75-L76

Will the gt misalignment between top-down map and perspective images hinder the performance of the surrounding branch of HDMapNet? And how to align the gt?
![image](https://user-images.githubusercontent.com/31960625/165669432-000fa653-622c-42b8-a509-64b978619cb4.png)

**Comment by LegendBC** [comment]
Thanks for your job again. I figured out that all the predictions were using BEV format, so as the GT. So the misalignment issue is somehow solved by the optimization of the model.

**Comment by Vishal1711** [comment]
@LegendBC  How you solved misalignment issue by optimization of model? Can you elaborate more about that?

**Comment by LegendBC** [comment]
> @LegendBC How you solved misalignment issue by optimization of model? Can you elaborate more about that?

@Vishal1711 The model predicts lines in BEV. The misalignment in perspective view is attributed to the absence of height in the ground truth (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_api.py#L1134-L1136). All the downstream tasks directly utilize the structured vector map in BEV.
