### ISSUE TITLE
Model Evaluation Correction

### ISSUE THREAD

**Issue by Vishal1711** [Tsinghua-MARS-Lab/HDMapNet#20]
To create submission file try to run -
```
python export_gt_to_json.py
```
After running above file you will get `submission.json` file.

To evaluate file
```
python evaluate_json.py --result_path [submssion_file_path]
```

Hope this will save time for those who getting stuck with `Readme` instructions

**Comment by Mrmoore98** [comment]
Thanks for you feedback, I have added it in the `Readme`.
