### ISSUE TITLE
Inconsistent Intrinsic Matrix in data fetching, probably leading to worse IPMNet performance

### ISSUE THREAD

**Issue by Owen-Liuyuxuan** [Tsinghua-MARS-Lab/HDMapNet#21]
Thank you for your amazing work.

I notice that there is a [resize operation](https://github.com/Tsinghua-MARS-Lab/HDMapNet/blob/7911227d45edb0226422083bc4bc452dc18e6399/data/dataset.py#L127) in the data fetching phase that shrinks the image size. 

However, to keep the projection relation between ground truth 3D lanes and the (resized)image pixels, we also need to adjust the camera intrinsic during the data fetching phase. (For example, if the image is downsampled by two, the first two rows of the intrinsic matrix should also become one half smaller)

In HDMapNet, because we use linear layers to learn the mapping between the front view and the BEV view, there is no need for intrinsic parameters, and the code works fine.

However, in IPMNet and Lift-Splat-Shoot, correct camera intrinsic parameters are essential to correctly project the FV features to BEV. The inconsistent camera intrinsic matrix could probably hurt the performance of IPMNet and LSS in the experiments mentioned in your paper. Did the ablation experiments in your paper also use the code in this repo to reproduce?

**Comment by Mrmoore98** [comment]
We have taken the effect of resize operation into consideration and updated the rotation and translation matrices [here](https://github.com/Tsinghua-MARS-Lab/HDMapNet/blob/7911227d45edb0226422083bc4bc452dc18e6399/data/image.py#L40-L43).

**Comment by Owen-Liuyuxuan** [comment]
Thank you for your explanation... It seems that post_RT is not a rotation/translation but a scale factor matrix (it is also set to None at HDMap, which also misdirects me a bit). 

The code flow seems correct after all. Many thanks.
