### ISSUE TITLE
About the IOU

### ISSUE THREAD

**Issue by Xiangzhaohong** [Tsinghua-MARS-Lab/HDMapNet#25]
TRAIN[  0]: [ 449/7031]    Time:  0.4546    Loss:  1.3768    IOU: [0.000 0.000 0.000]

this is log of my training, IOU is always 0.0
is that right?

**Comment by 611614637** [comment]
Same problem，how did you fix it?

**Comment by 172chen27** [comment]
Do you still have this problem? If so, how to solve it？
