### ISSUE TITLE
Will you release your training code?

### ISSUE THREAD

**Issue by lhcalibur** [Tsinghua-MARS-Lab/HDMapNet#3]
Hi, first thanks for your great job!
I wonder whether you will release your training code? thanks.

**Comment by TonyXuQAQ** [comment]
Yeah will you release the training code for reproducing?

**Comment by 0817-wangshuai** [comment]
GREAT JOB!!! same question, when will you release the whole code?

**Comment by patrick-llgc** [comment]
Yes, releasing the code would significantly advance this subfield of research. Congrats on the fabulous work! @hangzhaomit

**Comment by zhangjunliang1124** [comment]
great job!! Look forward to seeing the whole code?

**Comment by liqi17thu** [comment]
Sorry for the late response, we are working on releasing the training code now, and hopefully this month we will release it.
