### ISSUE TITLE
运行vis_pred.py  时报错

### ISSUE THREAD

**Issue by kd12138888** [Tsinghua-MARS-Lab/HDMapNet#30]

**Comment by kd12138888** [comment]
coords, _, _ = vectorize(segmentation[si], embedding[si], direction[si], angle_class)
TypeError: 'NoneType' object is not subscriptable
请问如何解决？

**Comment by kd12138888** [comment]
segmentation, embedding, direction = model(imgs.cuda(), trans.cuda(), rots.cuda(), intrins.cuda(),
                                                       post_trans.cuda(), post_rots.cuda(), lidar_data.cuda(),
                                                       lidar_mask.cuda(), car_trans.cuda(), yaw_pitch_roll.cuda())
其中embedding参数为空

**Comment by 2443138933** [comment]
--instance_seg和 --direction_pred都改成True

**Comment by kd12138888** [comment]
parser.add_argument('--instance_seg', action='store_true')
parser.add_argument('--direction_pred', action='store_true')
是这两个吗？  一开始就是ture

**Comment by 2443138933** [comment]
> parser.add_argument('--instance_seg', action='store_true') parser.add_argument('--direction_pred', action='store_true') 是这两个吗？ 一开始就是ture

action='store_true'改成default=True

**Comment by kd12138888** [comment]
非常感谢

**Comment by Yc174** [comment]
请问能公布一下训练好的model吗？ @2443138933 @kd12138888

**Comment by GoroYeh-HRI** [comment]
Hi, I also got the "embedding is NoneType" error and after setting to "default=True" it worked.
However, the evaluation result is pretty bad.
Also, even if I run `train.py` with those two parameters set to "default=True",
the IOU in trainning log is very low

![image](https://github.com/Tsinghua-MARS-Lab/HDMapNet/assets/137837175/add0bbd2-8efa-47d3-aa6b-86c67c067911)

my evaluation result:
![image](https://github.com/Tsinghua-MARS-Lab/HDMapNet/assets/137837175/9654bceb-0cb6-4e06-aea5-88a8b48af8ed)

Do you know what might be wrong in my training setup?
I use all default parameters settings.

**Comment by bjzhb666** [comment]
Hi. What do the three numbers in IOU list mean? Thanks
