### ISSUE TITLE
vis_segmentation_label.py AttributeError: 'Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by hzhv** [Tsinghua-MARS-Lab/HDMapNet#32]
How to figure this out, thx!

**Comment by xiaomouse2004** [comment]
May be you can do like this:

        semantic_mask = semantic_mask.numpy() * 255
        # semantic_mask = semantic_mask.astype('uint8') * 255
        semantic_mask = np.moveaxis(semantic_mask, 0, -1)
        Image.fromarray(np.uint8(semantic_mask)).save(semantic_path)

        # instance_mask = instance_mask.sum(0).astype('uint8')
        # instance_color_mask = color_map[instance_mask].astype('uint8')
        instance_mask = np.uint8(instance_mask.sum(0).numpy())
        instance_color_mask = color_map[instance_mask]
        Image.fromarray(np.uint8(instance_color_mask)).save(instance_path)

**Comment by hzhv** [comment]
@xiaomouse2004 Appreciated!
