### ISSUE TITLE
The vectorized visualization results are very bad, but the training accuracy is close to the accuracy proposed in the paper。

### ISSUE THREAD

**Issue by Bin-ze** [Tsinghua-MARS-Lab/HDMapNet#39]
![eval000003_002](https://user-images.githubusercontent.com/72087870/204417493-55d06872-8615-4ba2-8f97-359cfb419390.jpg)

**Comment by Terminal-K** [comment]
@Bin-ze Hi,  I am facing the same issue.Did you solve it?

**Comment by Bin-ze** [comment]
﻿
﻿Yes, I solved it. The reason is that the d way to generate the prediction split chart is inconsistent when training reasoning. Please change the reasoning to the same as the training.

发自我的iPhone

**Comment by dddtyz** [comment]
hi ，can you provide a code？ i have same question
