### ISSUE TITLE
vis_label.py not working

### ISSUE THREAD

**Issue by iacopo97** [Tsinghua-MARS-Lab/HDMapNet#47]
I am trying to use vis_label.py with nuScenes v1.0 mini dataset but it is not working.
This is the error
`
Traceback (most recent call last):
  File "/content/HDMapNet/vis_label.py", line 95, in <module>
    vis_label(args.dataroot, args.version, args.xbound, args.ybound)
  File "/content/HDMapNet/vis_label.py", line 24, in vis_label
    dataset = HDMapNetDataset(version=version, dataroot=dataroot, data_conf=data_conf, is_train=False)
  File "/content/HDMapNet/data/dataset.py", line 31, in __init__
    self.nusc = NuScenes(version=version, dataroot=dataroot, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: dataroot=/content/HDMapNet/dataset/nuScenes/v1.0-mini
`

**Comment by MostafaAhmed95** [comment]
Hello @iacopo97, I just were able to fix this issue, go to the following line in vis_label.py and change the first line with the second one
```
#parser.add_argument('dataroot',type=str,default='dataset/nuScenes/')
parser.add_argument('--dataroot', type=str, default='YOUR_data_set_directory')
```
don't forget also to download the nuscenes map expansion and the expansion folder inside your maps.

**Comment by SISTMrL** [comment]
> Hello @iacopo97, I just were able to fix this issue, go to the following line in vis_label.py and change the first line with the second one
> 
> ```
> #parser.add_argument('dataroot',type=str,default='dataset/nuScenes/')
> parser.add_argument('--dataroot', type=str, default='YOUR_data_set_directory')
> ```
> 
> don't forget also to download the nuscenes map expansion and the expansion folder inside your maps.

hello, could you please provide the visulization code of instance embedding map
