### ISSUE TITLE
Pytorch version does not exist

### ISSUE THREAD

**Issue by OpenSatMap** [Tsinghua-MARS-Lab/HDMapNet#52]
In [https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/), there is not torch=1.10.2+cu113

**Comment by BatyrM** [comment]
How did you solve the problem? Could you please share?

**Comment by bjzhb666** [comment]
Change the version of torch,torchvision.

**Comment by dlengerer** [comment]
I don't know why 1.10.2 is not listed in the previous versions, but the installation is [possible](https://discuss.pytorch.org/t/installing-pytorch/144240)

`pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`
