### ISSUE TITLE
Question on BEV decoder

### ISSUE THREAD

**Issue by Francis777** [Tsinghua-MARS-Lab/HDMapNet#6]
Hi, thanks for your great work! I have a question regarding your architecture of the BEV decoder, according to the paper: 
> The BEV decoder is a fully convolutional network with 3 branches, namely semantic segmentation branch, instance embedding branch, and direction prediction branch…ResNet with three blocks is used as the BEV decoder.

If I understand it right, the input BEV feature to the decoder has shape <img src="https://render.githubusercontent.com/render/math?math=[H_{\text{bev}}, W_{\text{bev}}, K]">, the segmentation branch has output shape <img src="https://render.githubusercontent.com/render/math?math=[H_{\text{bev}}, W_{\text{bev}}, K^{'}]"> (K' different for each branch). It's not very clear to me how a ResNet can be applied here. 

My guess is you use a U-Net structure with a shared encoder(which uses the last 3 encoders of ResNet with dilated convs to avoid downsampling) and a separate decoder for each branch, but this seems unnecessary given that the input is already a feature vector. Or do you mean each decoder is simply made up of 3 residual blocks? Thanks!

 
 Also as a minor request, could you upload `icon/car.png` so that we can run `vis_label.py` with the ego car icon included in the g.t. map label as well?

**Comment by clmforgit** [comment]
I guess it may be a similar structure as that in Lift-Splat-Shoot.

**Comment by Francis777** [comment]
> I guess it may be a similar structure as that in Lift-Splat-Shoot.

Thanks @clmforgit, that does make sense(if you're referring to https://github.com/nv-tlabs/lift-splat-shoot/blob/d74598cb51101e2143097ab270726a561f81f8fd/src/models.py#L90). Now my remaining question is do the three branches share the downsampling layers and only use separate upsampling layers?

**Comment by liqi17thu** [comment]
Hi, @Francis777 sorry for the late response. Yes, it's a similar structure as Lift-Splat-Shoot, and the three branches share the downsampling layers with separate upsampling layers. I also upload the car icon : )
